spring:
    datasource:
        url: ${SPRING_DATASOURCE_URL} #jdbc:mysql://${HIBERNATE_DB_HOST}:${HIBERNATE_DB_PORT}/${HIBERNATE_DB_NAME}?useSSL=false
        username: ${SPRING_DATASOURCE_USERNAME} # ${HIBERNATE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD} # ${HIBERNATE_PASSWORD}

    jpa:
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


# App Properties
jwtSecret: ${JWT_SECRET} # ${JWT_SECRET_KEY}
jwtExpirationMs: ${JWTEXPIRATIONMS} # ${JWT_EXPIRATION_TIME}
