
spring:
    datasource:
        url: jdbc:mysql://${HIBERNATE_DB_HOST}:${HIBERNATE_DB_PORT}/${HIBERNATE_DB_NAME}?useSSL=false
        username: ${HIBERNATE_USERNAME}
        password: ${HIBERNATE_PASSWORD}

    jpa:
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    rabbitmq:
        host: ${RABBITMQ_HOST}
        port: ${RABBITMQ_PORT}
        username: ${RABBITMQ_USERNAME}
        password: ${RABBITMQ_PASSWORD}

    redis:
        host: ${REDIS_HOST}
        port: ${REDIS_PORT}

# App Properties
jwtSecret: ${JWT_SECRET_KEY}
jwtExpirationMs: ${JWT_EXPIRATION_TIME}

rabbitmq:
    queue: queue1


